// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgbD74pDvbNS1ftfAtMuv5GQZr7grZ0Wo',
    appId: '1:883738531806:web:412781d59fae88459cef4f',
    messagingSenderId: '883738531806',
    projectId: 'authtutorial-781d1',
    authDomain: 'authtutorial-781d1.firebaseapp.com',
    storageBucket: 'authtutorial-781d1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUIg_GvGGSR0ChboIuEO0Hv7rYBYSwTAY',
    appId: '1:883738531806:android:f33d1229752a7a7d9cef4f',
    messagingSenderId: '883738531806',
    projectId: 'authtutorial-781d1',
    storageBucket: 'authtutorial-781d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvHlel5Ho-WDokvRwTTBm1VI7Kh6S2Pxw',
    appId: '1:883738531806:ios:be3850b8741a6f399cef4f',
    messagingSenderId: '883738531806',
    projectId: 'authtutorial-781d1',
    storageBucket: 'authtutorial-781d1.appspot.com',
    iosBundleId: 'com.example.parking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvHlel5Ho-WDokvRwTTBm1VI7Kh6S2Pxw',
    appId: '1:883738531806:ios:be3850b8741a6f399cef4f',
    messagingSenderId: '883738531806',
    projectId: 'authtutorial-781d1',
    storageBucket: 'authtutorial-781d1.appspot.com',
    iosBundleId: 'com.example.parking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgbD74pDvbNS1ftfAtMuv5GQZr7grZ0Wo',
    appId: '1:883738531806:web:b4c1b7588952f8769cef4f',
    messagingSenderId: '883738531806',
    projectId: 'authtutorial-781d1',
    authDomain: 'authtutorial-781d1.firebaseapp.com',
    storageBucket: 'authtutorial-781d1.appspot.com',
  );
}
