name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'
        java-package: jdk
        architecture: x64
        check-latest: false
        server-id: github
        server-username: ${{ github.actor }}
        server-password: ${{ secrets.GITHUB_TOKEN }}
        overwrite-settings: true
        job-status: success

    - name: Install dependencies
      run: sudo apt-get install -y lib32stdc++6 lib32z1

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'latest'

    - name: Flutter clean
      run: flutter clean

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: android-apk
        path: build/app/outputs/flutter-apk/app-release.apk

  build-ios:
    name: Build iOS
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'
        java-package: jdk
        architecture: x64
        check-latest: false
        server-id: github
        server-username: ${{ github.actor }}
        server-password: ${{ secrets.GITHUB_TOKEN }}
        overwrite-settings: true
        job-status: success

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'latest'

    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods
        pod setup

    - name: Flutter clean
      run: flutter clean

    - name: Install dependencies
      run: flutter pub get

    - name: Build iOS
      run: flutter build ios --release --no-codesign

    - name: Upload IPA
      uses: actions/upload-artifact@v2
      with:
        name: ios-app
        path: build/ios/ipa
