name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Install dependencies
      run: sudo apt-get install -y lib32stdc++6 lib32z1

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'

    - name: Flutter clean
      run: flutter clean

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: android-apk
        path: build/app/outputs/flutter-apk/app-release.apk

  build-ios:
    name: Build iOS
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'

    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods
        pod setup

    - name: Flutter clean
      run: flutter clean

    - name: Install dependencies
      run: flutter pub get

    - name: Build iOS
      run: flutter build ios --release --no-codesign

    - name: Upload IPA
      uses: actions/upload-artifact@v2
      with:
        name: ios-app
        path: build/ios/ipa/**/*.ipa

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [build-android, build-ios]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download Android APK
      uses: actions/download-artifact@v2
      with:
        name: android-apk
        path: ./artifacts

    - name: Download iOS IPA
      uses: actions/download-artifact@v2
      with:
        name: ios-app
        path: ./artifacts

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: 'v1.0.0'  # Tag for the release
        name: 'SantosParking v1.0.0'  # Name of the release
        body: 'Initial release of the app.'  # Release notes
        files: |
          ./artifacts/app-release.apk
          ./artifacts/*.ipa
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
